# Generated by Django 4.2.2 on 2023-07-05 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanPayment',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_code', models.CharField(max_length=50)),
                ('artisan_number', models.CharField(max_length=20)),
                ('transaction_date', models.DateTimeField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('artisan', models.ForeignKey(limit_choices_to={'usertype': 'artisan'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
