# Generated by Django 4.2.2 on 2023-07-05 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtisanPayment',
        ),
    ]
