# Generated by Django 4.2.2 on 2023-07-06 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers_api', '0004_rename_id_customerjobrequests_job_request_id'),
        ('payment_api', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanpayment',
            name='job_request_id',
            field=models.OneToOneField(default=7, on_delete=django.db.models.deletion.CASCADE, to='customers_api.customerjobrequests'),
            preserve_default=False,
        ),
    ]
