# Generated by Django 4.2.1 on 2023-05-23 13:06

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('specialization', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('plumber', 'plumber'), ('electrician', 'electrician'), ('carpenter', 'carpenter'), ('mason', 'mason'), ('tiling', 'tiling')], max_length=50), size=None)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('preferred_working_days', models.CharField(max_length=250)),
                ('preferred_working_hours', models.CharField(max_length=250)),
                ('preferred_daily_wage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('geolocation', models.CharField(max_length=50)),
                ('certifications', models.CharField(max_length=50)),
                ('qualifications', models.CharField(max_length=50)),
                ('id_verification', models.BooleanField(default=False)),
                ('referee_1_name', models.CharField(max_length=50)),
                ('referee_1_contact', models.CharField(max_length=50)),
                ('referee_2_name', models.CharField(max_length=50)),
                ('referee_2_contact', models.CharField(max_length=50)),
                ('referee_3_name', models.CharField(max_length=50)),
                ('referee_3_contact', models.CharField(max_length=50)),
                ('user', models.ForeignKey(limit_choices_to={'usertype': 'artisan'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
