# Generated by Django 4.2.1 on 2023-05-29 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artisans_api', '0004_artisanpersonalinfo_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisanpersonalinfo',
            name='user',
            field=models.OneToOneField(limit_choices_to={'usertype': 'artisan'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
