# Generated by Django 4.2.1 on 2023-05-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans_api', '0006_alter_artisanpersonalinfo_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisanpersonalinfo',
            name='specialization',
            field=models.CharField(choices=[('plumber', 'plumber'), ('electrician', 'electrician'), ('carpenter', 'carpenter'), ('mason', 'mason'), ('tiling', 'tiling'), ('painter', 'painter')], max_length=50),
        ),
    ]
