# Generated by Django 4.2.1 on 2023-06-02 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisans_api', '0010_artisanpersonalinfo_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisanpersonalinfo',
            name='profile_picture',
        ),
    ]
