# Generated by Django 4.2.1 on 2023-06-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerJobRequests',
        ),
    ]
