# Generated by Django 4.2.2 on 2023-07-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_api', '0004_rename_id_customerjobrequests_job_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerjobrequests',
            name='schedule',
            field=models.DateField(),
        ),
    ]
