# Generated by Django 4.2 on 2023-05-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_appuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='usertype',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
