# Generated by Django 4.2 on 2023-05-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_alter_appuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='usertype',
            field=models.CharField(choices=[('artisan', 'artisan'), ('customer', 'customer'), ('admin', 'admin')], max_length=20),
        ),
    ]
