# Generated by Django 4.2.1 on 2023-05-19 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0008_alter_appuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Only numbers are allowed', regex='^\\d{1,10}$')]),
        ),
    ]
