# Generated by Django 4.2.1 on 2023-05-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0009_alter_appuser_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name_plural': 'AppUsers'},
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
