# Generated by Django 4.2.1 on 2023-05-19 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0010_alter_appuser_options_alter_appuser_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={},
        ),
    ]
