# Generated by Django 4.2.1 on 2023-05-19 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0011_alter_appuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Only numbers are allowed', regex='^\\d{1,10}$')]),
        ),
    ]
