# Generated by Django 4.2.1 on 2023-05-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0012_alter_appuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
